Console.Writeline ("[Intro: yung lixo]");
Console.Writeline ("Bife, tá chovendo invejoso, meu");
Console.Writeline ("Tá chovendo invejoso do céu");
Console.Writeline ("Tá chovendo hambúrguer só que de invejoso, moleque");
Console.Writeline ("Tá foda, não tá dando nem pra segurar a barra");
Console.Writeline ("Sente só, ó!");

Console.Writeline ("[Verso 1: yung lixo]");
Console.Writeline ("Vou sair com ela na sexta no estilo putão");
Console.Writeline ("Com vontade extra inveja tem de montão");
Console.Writeline ("Esses caras têm muita, tá chovendo vagabundo carregado na minha nuca");
Console.Writeline ("Se eu me mexo eles caem no chão");
Console.Writeline ("Peço perdão pelas rimas diferente");
Console.Writeline ("Pelo flow arrojado еstilo despojado");
Console.Writeline ("Aquele soco quе eu te dei");
Console.Writeline ("É que eu esqueci de dar bola pra lei");
Console.Writeline ("[Ponte: yung lixo]");
Console.Writeline ("Te incomodei");
Console.Writeline ("'Cê bate o olho no clipe, mano, fui eu que editei");
Console.Writeline ("'Cê tá todo seco, mano, cadê o drip? Eu inundei");
Console.Writeline ("Como já dizia meu parceiro japonês, mano, no way");
Console.Writeline ("No way...");
Console.Writeline ("Te incomodei");
Console.Writeline ("'Cê bate o olho no clipe, mano, fui eu que editei");
Console.Writeline ("'Cê tá todo seco, mano, cadê o drip? Eu inundei");
Console.Writeline ("Como já dizia meu parceiro japonês, mano, no way");
Console.Writeline ("No way...");

Console.Writeline ("[Refrão: yung lixo]" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("Não sou mais um, você se pergunta como eu faço" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("'Cê me imita, mano, eu não sou mais um" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("A pedra se afunda, onde eu passo tipo Vegeta, eu não sou mais um" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("Dou tapa na nuca da polícia que me irrita, mano, eu não sou mais um" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("Não sou mais um, não sou mais um" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("Eu não sou mais um, você se pergunta como eu faço" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("'Cê me imita, mano, eu não sou mais um" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("A pedra se afunda, onde eu passo tipo Vegeta, eu não sou mais um" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("Dou tapa na nuca da polícia que me irrita, mano, eu não sou mais um" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("Não sou mais um, não sou mais um");

Console.Writeline ("[Verso 2: Biffe]");
Console.Writeline ("Ai, ai, ai, ai");
Console.Writeline ("E a inveja tem muita");
Console.Writeline ("De tanta rima foda que eu mandei nessa semana");
Console.Writeline ("Mano, tomei até multa");
Console.Writeline ("Tem mano que me xinga o dia inteiro");
Console.Writeline ("E quando me vê, só pede desculpa");
Console.Writeline ("Parece bem fácil chegar onde eu tô");
Console.Writeline ("Mas, mano, não se assusta");
Console.Writeline ("Quando tu ver que não é não");
Console.Writeline ("'Cês morre de inveja");
Console.Writeline ("As bitch me ouve no phone a cada minuto deseja");
Console.Writeline ("Os trapper que ouve meu som se chateia, porque ele lidera");
Console.Writeline ("Yung no topo, aceita me ouve ou então faz dieta");
Console.Writeline ("E fica chorando no chão");
Console.Writeline ("Não entendo essa gente que vive falando que não me entende");
Console.Writeline ("Fica reclamando, vê se te consente e põe na tua mente");
Console.Writeline ("Que eu tô no topo, que agora eu tô quente");
Console.Writeline ("Sei que infelizmente nada te convence");
Console.Writeline ("Mas eu não me importo porque eu tô na frente");
Console.Writeline ("Eu sou diferente, 'cê sabe, 'cê sente, não adianta negar");

Console.Writeline ("[Refrão: yung lixo]" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("Não sou mais um, você se pergunta como eu faço" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("'Cê me imita, mano, eu não sou mais um" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("A pedra se afunda, onde eu passo tipo Vegeta, eu não sou mais um" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("Dou tapa na nuca da polícia que me irrita, mano, eu não sou mais um" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("Não sou mais um, não sou mais um" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("Eu não sou mais um, você se pergunta como eu faço" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("'Cê me imita, mano, eu não sou mais um" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("A pedra se afunda, onde eu passo tipo Vegeta, eu não sou mais um" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("Dou tapa na nuca da polícia que me irrita, mano, eu não sou mais um" foreground color = ConsoleColor.Turquoise);
Console.Writeline ("Não sou mais um, não sou mais um" foreground color = ConsoleColor.Turquoise);